### ISSUE TITLE
Nokogiri (load error)

### ISSUE THREAD

**Issue by Brick-T0p** [Gr4y-r0se/nedit#1]
Below error after running bundle install, and still same error after running gem install nokogiri:

└─$ ruby nedit.rb -h
<internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- Nokogiri (LoadError)
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /opt/nedit/modules/csv.rb:1:in `<top (required)>'
        from nedit.rb:3:in `require_relative'
        from nedit.rb:3:in `<main>'

**Comment by Brick-T0p** [comment]
This was on Kali 2022.2

**Comment by Gr4y-r0se** [comment]
Hi Brick-T0p, thanks for raising this - v1.2.0 fixes this issue!

**Comment by Brick-T0p** [comment]
No worries Liam :) , I think I worked it out in the end anyway (there were some capital letter that shouldn't have been capitals or vice versa)
